name: rails-ci

on: pull_request

jobs:
  run-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3

      - name: install bundler2
        run: gem install bundler

      - name: Install dependencies
        run: sudo apt-get install libpq-dev xpdf

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Install npm dependencies
        run: bin/rails yarn:install

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Run rspec
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          QR_SERVER: ${{ secrets.QR_SERVER }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
